// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: api/limiter.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus int32

const (
	ResponseStatus_STATUS_SUCCESS ResponseStatus = 0
	ResponseStatus_STATUS_FAILED  ResponseStatus = 1
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "STATUS_SUCCESS",
		1: "STATUS_FAILED",
	}
	ResponseStatus_value = map[string]int32{
		"STATUS_SUCCESS": 0,
		"STATUS_FAILED":  1,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_limiter_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_api_limiter_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{0}
}

type DetectBruteforceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip       string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *DetectBruteforceRequest) Reset() {
	*x = DetectBruteforceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_limiter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectBruteforceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectBruteforceRequest) ProtoMessage() {}

func (x *DetectBruteforceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_limiter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectBruteforceRequest.ProtoReflect.Descriptor instead.
func (*DetectBruteforceRequest) Descriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *DetectBruteforceRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *DetectBruteforceRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DetectBruteforceRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type DetectBruteforceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Detected bool `protobuf:"varint,1,opt,name=detected,proto3" json:"detected,omitempty"`
}

func (x *DetectBruteforceResponse) Reset() {
	*x = DetectBruteforceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_limiter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectBruteforceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectBruteforceResponse) ProtoMessage() {}

func (x *DetectBruteforceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_limiter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectBruteforceResponse.ProtoReflect.Descriptor instead.
func (*DetectBruteforceResponse) Descriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *DetectBruteforceResponse) GetDetected() bool {
	if x != nil {
		return x.Detected
	}
	return false
}

type ResetBucketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Logins []string `protobuf:"bytes,1,rep,name=logins,proto3" json:"logins,omitempty"`
	Ips    []string `protobuf:"bytes,2,rep,name=ips,proto3" json:"ips,omitempty"`
}

func (x *ResetBucketRequest) Reset() {
	*x = ResetBucketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_limiter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetBucketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketRequest) ProtoMessage() {}

func (x *ResetBucketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_limiter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketRequest.ProtoReflect.Descriptor instead.
func (*ResetBucketRequest) Descriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{2}
}

func (x *ResetBucketRequest) GetLogins() []string {
	if x != nil {
		return x.Logins
	}
	return nil
}

func (x *ResetBucketRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

type ResetBucketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
}

func (x *ResetBucketResponse) Reset() {
	*x = ResetBucketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_limiter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetBucketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetBucketResponse) ProtoMessage() {}

func (x *ResetBucketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_limiter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetBucketResponse.ProtoReflect.Descriptor instead.
func (*ResetBucketResponse) Descriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{3}
}

func (x *ResetBucketResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_STATUS_SUCCESS
}

type ManageAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Mask string `protobuf:"bytes,2,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *ManageAddressRequest) Reset() {
	*x = ManageAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_limiter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManageAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageAddressRequest) ProtoMessage() {}

func (x *ManageAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_limiter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageAddressRequest.ProtoReflect.Descriptor instead.
func (*ManageAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{4}
}

func (x *ManageAddressRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ManageAddressRequest) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

type ManageAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=api.ResponseStatus" json:"status,omitempty"`
}

func (x *ManageAddressResponse) Reset() {
	*x = ManageAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_limiter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManageAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManageAddressResponse) ProtoMessage() {}

func (x *ManageAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_limiter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManageAddressResponse.ProtoReflect.Descriptor instead.
func (*ManageAddressResponse) Descriptor() ([]byte, []int) {
	return file_api_limiter_proto_rawDescGZIP(), []int{5}
}

func (x *ManageAddressResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_STATUS_SUCCESS
}

var File_api_limiter_proto protoreflect.FileDescriptor

var file_api_limiter_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x5b, 0x0a, 0x17, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x42, 0x72, 0x75, 0x74, 0x65, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x70, 0x22, 0x36, 0x0a, 0x18, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x42,
	0x72, 0x75, 0x74, 0x65, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x08, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x22, 0x3e, 0x0a,
	0x12, 0x52, 0x65, 0x73, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x69,
	0x70, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73, 0x22, 0x42, 0x0a,
	0x13, 0x52, 0x65, 0x73, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x3a, 0x0a, 0x14, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x22, 0x44, 0x0a,
	0x15, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x2a, 0x37, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x32, 0xc6, 0x03, 0x0a,
	0x07, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x12, 0x4f, 0x0a, 0x10, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x42, 0x72, 0x75, 0x74, 0x65, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x42, 0x72, 0x75, 0x74, 0x65, 0x66, 0x6f,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x42, 0x72, 0x75, 0x74, 0x65, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x0b, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x57,
	0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64, 0x49, 0x50, 0x12, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x61, 0x6e, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x57, 0x68, 0x69, 0x74, 0x65, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x50, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x47, 0x0a, 0x0e, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x64,
	0x49, 0x50, 0x12, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x11, 0x42, 0x6c, 0x61,
	0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x50, 0x12, 0x19,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_limiter_proto_rawDescOnce sync.Once
	file_api_limiter_proto_rawDescData = file_api_limiter_proto_rawDesc
)

func file_api_limiter_proto_rawDescGZIP() []byte {
	file_api_limiter_proto_rawDescOnce.Do(func() {
		file_api_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_limiter_proto_rawDescData)
	})
	return file_api_limiter_proto_rawDescData
}

var file_api_limiter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_limiter_proto_goTypes = []interface{}{
	(ResponseStatus)(0),              // 0: api.ResponseStatus
	(*DetectBruteforceRequest)(nil),  // 1: api.DetectBruteforceRequest
	(*DetectBruteforceResponse)(nil), // 2: api.DetectBruteforceResponse
	(*ResetBucketRequest)(nil),       // 3: api.ResetBucketRequest
	(*ResetBucketResponse)(nil),      // 4: api.ResetBucketResponse
	(*ManageAddressRequest)(nil),     // 5: api.ManageAddressRequest
	(*ManageAddressResponse)(nil),    // 6: api.ManageAddressResponse
}
var file_api_limiter_proto_depIdxs = []int32{
	0, // 0: api.ResetBucketResponse.status:type_name -> api.ResponseStatus
	0, // 1: api.ManageAddressResponse.status:type_name -> api.ResponseStatus
	1, // 2: api.Limiter.DetectBruteforce:input_type -> api.DetectBruteforceRequest
	3, // 3: api.Limiter.ResetBucket:input_type -> api.ResetBucketRequest
	5, // 4: api.Limiter.WhiteListAddIP:input_type -> api.ManageAddressRequest
	5, // 5: api.Limiter.WhiteListRemoveIP:input_type -> api.ManageAddressRequest
	5, // 6: api.Limiter.BlackListAddIP:input_type -> api.ManageAddressRequest
	5, // 7: api.Limiter.BlackListRemoveIP:input_type -> api.ManageAddressRequest
	2, // 8: api.Limiter.DetectBruteforce:output_type -> api.DetectBruteforceResponse
	4, // 9: api.Limiter.ResetBucket:output_type -> api.ResetBucketResponse
	6, // 10: api.Limiter.WhiteListAddIP:output_type -> api.ManageAddressResponse
	6, // 11: api.Limiter.WhiteListRemoveIP:output_type -> api.ManageAddressResponse
	6, // 12: api.Limiter.BlackListAddIP:output_type -> api.ManageAddressResponse
	6, // 13: api.Limiter.BlackListRemoveIP:output_type -> api.ManageAddressResponse
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_limiter_proto_init() }
func file_api_limiter_proto_init() {
	if File_api_limiter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_limiter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectBruteforceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_limiter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectBruteforceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_limiter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetBucketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_limiter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetBucketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_limiter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManageAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_limiter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManageAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_limiter_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_limiter_proto_goTypes,
		DependencyIndexes: file_api_limiter_proto_depIdxs,
		EnumInfos:         file_api_limiter_proto_enumTypes,
		MessageInfos:      file_api_limiter_proto_msgTypes,
	}.Build()
	File_api_limiter_proto = out.File
	file_api_limiter_proto_rawDesc = nil
	file_api_limiter_proto_goTypes = nil
	file_api_limiter_proto_depIdxs = nil
}
