name: pipeline

on:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "current_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Setup Go
        uses: action/setup-go@v3
        with:
              go-version: 1.18

      - name: Linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.41.1
          working-directory: ${{env.current_branch}}

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "current_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Run tests with race detection
        run: go test -v -count 100 -race -timeout=1m ./...
        working-directory: ${{env.current_branch}}

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        run: echo "current_branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Build with makefile
        run: make build
        working-directory: ${{env.current_branch}}